apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-ontologi-indexer
  namespace: default
  labels:
    team: teampam
spec:
  image: repo.adeo.no:5443/pam-ontologi-indexer
  port: 9023
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  prometheus:
    enabled: true
    path: /internal/actuator/prometheus
  liveness:
    initialDelay: 60
    path: /internal/isAlive
  readiness:
    initialDelay: 60
    path: /internal/isReady
  resources:
    limits:
      cpu: 1000m
      memory: 1000Mi
    requests:
      cpu: 500m
      memory: 500Mi
  webproxy: false
  vault:
    enabled: true
  ingresses:
    - https://pam-ontologi-indexer.nais.oera-q.local
  env:
    - name: PAM_SYNONYMER_TYPEAHEAD_URL
      value: https://api-gw-q0.oera.no/pam-ontologi-synonymer/rest/typeahead
    - name: PAM_ES_URL
      value: https://tpa-stilling-opendistro-elasticsearch.nais.oera-q.local
